/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef USERSPACE_BAKE_CONFIG_H
#define USERSPACE_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Headers of private dependencies */
#ifdef USERSPACE_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef USERSPACE_STATIC
  #if USERSPACE_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define USERSPACE_EXPORT __declspec(dllexport)
  #elif USERSPACE_IMPL
    #define USERSPACE_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define USERSPACE_EXPORT __declspec(dllimport)
  #else
    #define USERSPACE_EXPORT
  #endif
#else
  #define USERSPACE_EXPORT
#endif

#endif

