/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef UI_BAKE_CONFIG_H
#define UI_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <Jobs>

/* Headers of private dependencies */
#ifdef UI_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if UI_IMPL && defined _MSC_VER
#define UI_EXPORT __declspec(dllexport)
#elif UI_IMPL
#define UI_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define UI_EXPORT __declspec(dllimport)
#else
#define UI_EXPORT
#endif

#endif

